backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin

media_folder: "src/gfx"

site_url: https://cld.silvestar.codes
display_url: https://cld.silvestar.codes
logo_url: https://cld.silvestar.codes/gfx/svg/cld-logo.svg

collections:
  - name: "setup"
    label: "Setup"
    files:
      - name: "data"
        label: "Data"
        file: "data/lines.json"
        format: "json"
        delete: false
        fields:
          - label: "Lines"
            label_singular: "Line"
            name: "list"
            widget: "list"
            fields:
              - label: "Line of code"
                name: "line"
                widget: "string"
                required: true
              - label: "Note"
                name: "note"
                widget: "text"
                required: true
              - label: "Link"
                name: "link"
                widget: "string"
                required: true
              - label: "Language"
                name: "language"
                widget: "string"
                required: true
              - label: "Author"
                name: "author"
                widget: "string"
              - label: "Twitter handle"
                name: "handle"
                widget: "string"
                required: true
              - label: "Date"
                name: "date"
                widget: "date"
                format: "YYYY-MM-DD"
                required: true

