backend:
  name: git-gateway
  branch: develop

media_folder: "gfx"

media_library:
  name: "uploadcare"

logo_url: https://cld.silvestar.codes/gfx/svg/cld.svg

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "setup"
    label: "Setup"
    files:
    - name: "data"
      label: "Data"
      file: "data/data.json"
      format: "json"
      fields:
        - label: "Line of code"
          name: "line"
          widget: "string"
          required: true
        - label: "Note"
          name: "note"
          widget: "text"
          required: true
        - label: "Language"
          name: "language"
          widget: "string"
          required: true
        - label: "Author"
          name: "author"
          widget: "string"
          required: true
        - label: "Email"
          name: "email"
          widget: "string"
          required: true
        - label: "Bio"
          name: "bio"
          widget: "string"
          required: false

