[build]
  # base = "./"
  publish = "dist"
  command = "rm -rf ./src/gfx/cover/* && npm run build"
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cld/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
