[build]
  base = "./"
  publish = "./dist/"
  command = "rm -rf src/gfx/cover/*.png && yarn build"
  functions = "./api/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
