backend:
  name: git-gateway
  branch: develop
  accept_roles:
    - admin
    - user

media_folder: "src/gfx"

site_url: https://cld.silvestar.codes
display_url: https://cld.silvestar.codes
logo_url: https://cld.silvestar.codes/gfx/svg/cld-logo.svg

collections:
  - name: "lines"
    label: "Lines"
    folder: "contribute"
    create: true
    delete: false
    extension: json
    format: json
    identifier_field: line
    slug: "{{year}}-{{month}}-{{day}}-{{line}}-{{author}}"
    fields:
      - label: "Line of code"
        name: "line"
        widget: "string"
      - label: "Note"
        name: "note"
        widget: "text"
      - label: "Link"
        name: "link"
        widget: "string"
      - label: "Language"
        name: "language"
        widget: "string"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "Email"
        name: "email"
        widget: "string"
      - label: "Bio"
        name: "bio"
        widget: "string"

